source 'https://rubygems.org'

group :test do
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'cucumber'
  gem 'geckodriver-helper'
  gem 'rake'
  gem 'rspec'
  gem 'selenium-webdriver', '3.142.7'
end