source 'https://rubygems.org'

group :test do
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'cucumber', "4.1.0"
  gem 'rake'
  gem 'rspec'
  gem 'selenium-webdriver', '3.142.7'
  gem 'site_prism'
  gem 'webdrivers'
end