source 'https://rubygems.org'

group :test do
  gem 'ffi', '< 1.17.0'
  gem 'capybara', '3.36.0'
  gem 'capybara-screenshot'
  gem 'cucumber'
  gem 'rake'
  gem 'rspec'
  gem 'selenium-webdriver', '3.142.7'
  gem 'webdrivers'
end
